name: Go

on: [push, pull_request]

jobs:
  checkout:
   runs-on: ubuntu-latest
   steps:
   - name: Check out code into the Go module directory
     uses: actions/checkout@v2 
  
  container_test:
    runs-on: ubuntu-latest
    needs: [checkout]
    container:
      image: justinisrael/opencolorigo:test
    steps:
      - name: Test 
        run: go test -count=1 -v
      
  test:
    name: Test
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Get dependencies
      run: |
        sudo apt-get install --no-install-recommends -y -q g++ libopencolorio-dev

    - name: Test
      run: go test -v -count=1 .
