name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: justinisrael/opencolorigo:test
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2 
      - name: Test 
        run: go test -count=1 -v
  
